#!/usr/bin/env node
// dial9 trace analysis script — generated by `dial9-viewer agents analyze`
// Usage: node analyze.js <trace.bin or directory>
//   --force    Ignore cached results and re-parse all files
//   --sample N Only analyze N evenly-spaced files from a directory
// Modify this script to drill deeper into specific findings.

const fs = require('fs');
const path = require('path');

// Resolve toolkit files: sibling (toolkit copy) or ui/ (source tree)
function resolve(name) {
  const sibling = path.resolve(__dirname, name);
  if (fs.existsSync(sibling)) return sibling;
  return path.resolve(__dirname, '..', 'ui', name);
}

const { parseTrace, EVENT_TYPES, formatFrame, symbolizeChain, deduplicateSamples } = require(resolve('trace_parser.js'));
const { buildWorkerSpans, attachCpuSamples, buildActiveTaskTimeline,
        computeSchedulingDelays, filterPointsOfInterest } = require(resolve('trace_analysis.js'));

const TRACE_PATH = process.argv[2];
if (!TRACE_PATH) { console.error('Usage: node analyze.js <trace.bin or directory>'); process.exit(1); }

// Parse CLI flags
const FORCE = process.argv.includes('--force');
const sampleIdx = process.argv.indexOf('--sample');
const SAMPLE = sampleIdx !== -1 ? Number(process.argv[sampleIdx + 1]) : null;

// ── Helpers ──

function maxBy(arr, fn) { return arr.reduce((m, x) => Math.max(m, fn(x)), -Infinity); }
function minBy(arr, fn) { return arr.reduce((m, x) => Math.min(m, fn(x)), Infinity); }

/** Classify a symbol as kernel, libc, allocator, tokio-runtime, or application code */
function frameKind(sym) {
  if (!sym || sym.startsWith('0x')) return 'unknown';
  // C symbols (no :: separator) — check libc first to avoid __GI_ matching kernel __
  if (!sym.includes('::')) {
    if (/^(__GI_|__libc_|__pthread_|__clone|start_thread|__poll|__epoll|__futex|malloc|free|mmap|munmap|brk|sbrk)/.test(sym)) return 'libc';
    if (/^(je_|arena_|tcache_|extent_|large_|slab_|jemalloc)/.test(sym) || /^(mi_|_mi_|mi_heap_|mimalloc)/.test(sym)) return 'allocator';
    if (/^(__|do_|sys_|entry_|exit_to|irq_|page_|rcu_|synchronize_)/.test(sym)) return 'kernel';
    if (/^(schedule|expand_fd|expand_files|alloc_fd|ep_poll|ep_send|futex_|sock_|inet_|tcp_|vfs_|filp_|fd_install|ksys_|fput|fget)/.test(sym)) return 'kernel';
  }
  // Tokio runtime internals
  if (/^tokio::runtime::(scheduler|task|blocking|context|coop)/.test(sym)) return 'runtime';
  if (/^std::(panicking|sys|thread)::/.test(sym)) return 'runtime';
  return 'app';
}

/** Walk a symbolized stack to find the interesting frames:
 *  - The syscall (first libc frame)
 *  - The blocking kernel operation (kernel frame that isn't generic plumbing)
 *  - The first application frame that triggered it
 *  Returns { syscall, blocker, trigger, classified } */
function diagnoseStack(frames) {
  let syscall = null;
  let trigger = null;
  let blocker = null;
  const classified = frames.map(f => ({ ...f, kind: frameKind(f.symbol), display: formatFrame(f).text }));

  // Generic kernel plumbing — not the interesting part
  const PLUMBING = /^(__schedule|schedule$|schedule_timeout|do_syscall_64|entry_SYSCALL|__x64_sys_|__sys_|__wait_for_common|__wait_rcu_gp)/;

  for (let i = 0; i < classified.length; i++) {
    const f = classified[i];
    if (!syscall && f.kind === 'libc') syscall = f;
    if (!blocker && f.kind === 'kernel' && !PLUMBING.test(f.symbol)) blocker = f;
    if (!trigger && f.kind === 'app') { trigger = f; break; }
  }
  return { syscall, blocker, trigger, classified };
}

function fmtDur(ns) {
  if (ns >= 1e9) return (ns / 1e9).toFixed(2) + 's';
  if (ns >= 1e6) return (ns / 1e6).toFixed(2) + 'ms';
  if (ns >= 1e3) return (ns / 1e3).toFixed(1) + 'µs';
  return ns + 'ns';
}

function fmtRel(ns, minTs) { return fmtDur(ns - minTs); }

// ── Main ──

/** Run the full analysis report for a single parsed trace. */
function analyzeOne(trace, label) {
  const workerIds = [...new Set(
    trace.events.filter(e => e.eventType !== EVENT_TYPES.QueueSample && e.eventType !== EVENT_TYPES.WakeEvent)
      .map(e => e.workerId)
  )].sort((a, b) => a - b);

  const minTs = minBy(trace.events, e => e.timestamp);
  const maxTs = maxBy(trace.events, e => e.timestamp);
  const durationMs = (maxTs - minTs) / 1e6;

  // Run full analysis pipeline
  const spans = buildWorkerSpans(trace.events, workerIds, maxTs);
  attachCpuSamples(trace.cpuSamples, spans.workerSpans);
  const taskTimeline = buildActiveTaskTimeline(trace.taskSpawnTimes, trace.taskTerminateTimes);
  const schedDelays = computeSchedulingDelays(spans.workerSpans, workerIds, spans.wakesByTask);

  reportAnalysis({
    workerIds, minTs, maxTs, durationMs,
    eventCount: trace.events.length,
    cpuSampleCount: trace.cpuSamples.length,
    taskSpawnCount: trace.taskSpawnTimes.size,
    taskAliveAtEnd: trace.taskSpawnTimes.size - trace.taskTerminateTimes.size,
    workerSpans: spans.workerSpans,
    queueSamples: spans.queueSamples,
    maxLocalQueue: spans.maxLocalQueue,
    schedDelays,
    taskTimeline,
    taskSpawnLocs: trace.taskSpawnLocs,
    taskSpawnTimes: trace.taskSpawnTimes,
    taskTerminateTimes: trace.taskTerminateTimes,
    callframeSymbols: trace.callframeSymbols,
    onCpuSampleCount: trace.cpuSamples.filter(s => s.source === 0).length,
    offCpuSampleCount: trace.cpuSamples.filter(s => s.source === 1).length,
    cpuGroups: deduplicateSamples(trace.cpuSamples.filter(s => s.source === 0), trace.callframeSymbols),
    schedGroups: deduplicateSamples(trace.cpuSamples.filter(s => s.source === 1), trace.callframeSymbols),
  }, label);
}

/** Print analysis report from pre-computed results. */
function reportAnalysis(a, label) {
  const { workerIds, minTs, durationMs, workerSpans, schedDelays, taskTimeline,
          callframeSymbols, taskSpawnLocs, taskSpawnTimes, taskTerminateTimes } = a;

  console.log(`\n${'='.repeat(60)}`);
  console.log(`TRACE SUMMARY: ${label}`);
  console.log(`${'='.repeat(60)}`);
  console.log(`Duration:       ${durationMs.toFixed(1)}ms`);
  console.log(`Workers:        ${workerIds.length} (IDs: ${workerIds.join(', ')})`);
  console.log(`Events:         ${a.eventCount.toLocaleString()}`);
  console.log(`CPU samples:    ${a.cpuSampleCount.toLocaleString()}`);
  console.log(`Tasks spawned:  ${a.taskSpawnCount}`);
  console.log(`Tasks alive at end: ${a.taskAliveAtEnd}`);

  // ── Worker utilization ──
  console.log(`\n${'─'.repeat(60)}`);
  console.log(`WORKER UTILIZATION`);
  console.log(`${'─'.repeat(60)}`);
  for (const w of workerIds) {
    const s = workerSpans[w];
    const activeNs = s.actives.reduce((sum, a) => sum + (a.end - a.start), 0);
    const parkNs = s.parks.reduce((sum, p) => sum + (p.end - p.start), 0);
    const total = activeNs + parkNs;
    const util = total > 0 ? (activeNs / total * 100).toFixed(1) : '0.0';
    const avgCpu = s.actives.length > 0
      ? (s.actives.reduce((sum, a) => sum + a.ratio, 0) / s.actives.length).toFixed(3) : 'N/A';
    console.log(`  Worker ${w}: ${util}% active, ${s.polls.length} polls, ${s.parks.length} parks, avg CPU ratio: ${avgCpu}`);
  }

  // ── Long polls ──
  console.log(`\n${'─'.repeat(60)}`);
  console.log(`LONG POLLS (>1ms)`);
  console.log(`${'─'.repeat(60)}`);
  const longPolls = [];
  for (const w of workerIds) {
    for (const p of workerSpans[w].polls) {
      const dur = p.end - p.start;
      if (dur > 1e6) longPolls.push({ dur, poll: p, worker: w });
    }
  }
  longPolls.sort((a, b) => b.dur - a.dur);

  if (longPolls.length === 0) {
    console.log('  None found ✅');
  } else {
    console.log(`  Found ${longPolls.length} long poll(s)\n`);
    for (const lp of longPolls.slice(0, 10)) {
      const p = lp.poll;
      console.log(`  ▸ ${fmtDur(lp.dur)} on worker ${lp.worker} at ${fmtRel(p.start, minTs)}`);
      console.log(`    Task ${p.taskId}, spawn: ${p.spawnLoc || '(unknown)'}`);

      // Deep-dive: scheduling samples show WHY the poll was long
      if (p.schedSamples?.length) {
        console.log(`    ${p.schedSamples.length} scheduling sample(s) — blocking call stacks:`);
        for (const s of p.schedSamples) {
          const frames = symbolizeChain(s.callchain, callframeSymbols);
          const { syscall, blocker, trigger, classified } = diagnoseStack(frames);
          if (blocker) {
            console.log(`      Blocked by:  ${blocker.symbol} (kernel)`);
          }
          if (syscall) console.log(`      Syscall:     ${syscall.display}`);
          if (trigger) {
            console.log(`      Called from:  ${trigger.display}`);
            if (trigger.location) console.log(`        at ${trigger.location}`);
          }
          // Show the kernel path that explains the delay
          const kernelPath = classified.filter(f => f.kind === 'kernel').map(f => f.symbol);
          if (kernelPath.length > 1) {
            console.log(`      Kernel path: ${kernelPath.join(' → ')}`);
          }
          // Print condensed app stack (skip runtime/unknown, collapse long runs)
          const appFrames = classified.filter(f => f.kind === 'app');
          if (appFrames.length > 0) {
            console.log(`      App call chain (${appFrames.length} frames):`);
            // Show first 3 (closest to syscall) and last 3 (entry point)
            const show = appFrames.length <= 8 ? appFrames : [
              ...appFrames.slice(0, 3),
              { display: `... ${appFrames.length - 6} more frames ...`, kind: 'ellipsis' },
              ...appFrames.slice(-3),
            ];
            for (const f of show) {
              console.log(`        ${f.display}`);
            }
          }
        }
      }
      if (p.cpuSamples?.length) {
        console.log(`    ${p.cpuSamples.length} CPU sample(s) — on-CPU stacks:`);
        for (const s of p.cpuSamples.slice(0, 3)) {
          const frames = symbolizeChain(s.callchain, callframeSymbols);
          const { trigger } = diagnoseStack(frames);
          if (trigger) console.log(`      ${trigger.display}`);
        }
      }
      if (!p.schedSamples?.length && !p.cpuSamples?.length) {
        console.log(`    (no profiling samples captured during this poll)`);
      }
      console.log();
    }
  }

  // ── Scheduling delays ──
  console.log(`${'─'.repeat(60)}`);
  console.log(`SCHEDULING DELAYS (wake → poll latency)`);
  console.log(`${'─'.repeat(60)}`);
  const highDelays = schedDelays.filter(d => d.delay > 1e6);
  if (highDelays.length === 0) {
    console.log('  No delays > 1ms ✅');
  } else {
    highDelays.sort((a, b) => b.delay - a.delay);
    console.log(`  ${highDelays.length} delays > 1ms`);
    console.log(`  Worst: ${fmtDur(highDelays[0].delay)}`);
    console.log(`  p50:   ${fmtDur(highDelays[Math.floor(highDelays.length * 0.5)]?.delay || 0)}`);
    console.log(`  p99:   ${fmtDur(highDelays[Math.floor(highDelays.length * 0.01)]?.delay || 0)}`);
    console.log(`\n  Top 5 worst:`);
    for (const d of highDelays.slice(0, 5)) {
      console.log(`    ${fmtDur(d.delay)} — task ${d.taskId} (spawn: ${d.poll.spawnLoc || '?'}) at ${fmtRel(d.wakeTime, minTs)}`);
    }
  }

  // ── Task lifecycle ──
  console.log(`\n${'─'.repeat(60)}`);
  console.log(`TASK LIFECYCLE`);
  console.log(`${'─'.repeat(60)}`);
  const spawnCounts = new Map();
  for (const [, loc] of taskSpawnLocs) {
    spawnCounts.set(loc || '(unknown)', (spawnCounts.get(loc || '(unknown)') || 0) + 1);
  }
  console.log('  Spawns by location:');
  for (const [loc, count] of [...spawnCounts.entries()].sort((a, b) => b[1] - a[1])) {
    console.log(`    ${String(count).padStart(5)} × ${loc}`);
  }

  // Task leak check
  const atSamples = taskTimeline.activeTaskSamples;
  if (atSamples.length > 0) {
    const peak = maxBy(atSamples, s => s.count);
    const final_ = atSamples[atSamples.length - 1].count;
    console.log(`\n  Peak active tasks: ${peak}`);
    console.log(`  Active at trace end: ${final_}`);
    if (final_ > atSamples[0].count * 2 && final_ === peak) {
      console.log('  ⚠ POSSIBLE TASK LEAK — active count grew monotonically');
      const alive = new Map();
      for (const [taskId] of taskSpawnTimes) {
        if (!taskTerminateTimes.has(taskId)) {
          const loc = taskSpawnLocs.get(taskId) || '(unknown)';
          alive.set(loc, (alive.get(loc) || 0) + 1);
        }
      }
      for (const [loc, count] of [...alive.entries()].sort((a, b) => b[1] - a[1])) {
        console.log(`    ${count} leaked from ${loc}`);
      }
    }
  }

  // ── Blocking calls (off-CPU samples) ──
  console.log(`\n${'─'.repeat(60)}`);
  console.log(`BLOCKING CALLS (scheduling/off-CPU samples)`);
  console.log(`${'─'.repeat(60)}`);
  if (a.offCpuSampleCount === 0) {
    console.log('  No off-CPU samples in trace');
  } else {
    console.log(`  ${a.offCpuSampleCount} off-CPU sample(s)\n`);
    for (const g of a.schedGroups.slice(0, 10)) {
      const pct = (g.count / a.offCpuSampleCount * 100).toFixed(1);
      const { syscall, blocker, trigger } = diagnoseStack(g.frames);
      console.log(`  ${String(g.count).padStart(5)} samples (${pct}%) — leaf: ${g.leaf}`);
      if (blocker) console.log(`         blocked by: ${blocker.symbol} (kernel)`);
      if (syscall) console.log(`         syscall:    ${syscall.display}`);
      if (trigger) console.log(`         called from: ${trigger.display}`);
    }
  }

  // ── CPU hotspots ──
  console.log(`\n${'─'.repeat(60)}`);
  console.log(`CPU HOTSPOTS (on-CPU samples)`);
  console.log(`${'─'.repeat(60)}`);
  if (a.onCpuSampleCount === 0) {
    console.log('  No CPU samples in trace');
  } else {
    console.log(`  ${a.onCpuSampleCount} CPU sample(s)\n`);
    for (const g of a.cpuGroups.slice(0, 10)) {
      const pct = (g.count / a.onCpuSampleCount * 100).toFixed(1);
      const { trigger } = diagnoseStack(g.frames);
      console.log(`  ${String(g.count).padStart(5)} samples (${pct}%) — leaf: ${g.leaf}`);
      if (trigger) console.log(`         app frame: ${trigger.display}`);
    }
  }

  // ── Queue depth ──
  console.log(`\n${'─'.repeat(60)}`);
  console.log(`QUEUE DEPTH`);
  console.log(`${'─'.repeat(60)}`);
  if (a.queueSamples.length > 0) {
    const maxQ = maxBy(a.queueSamples, s => s.global);
    const avgQ = a.queueSamples.reduce((s, q) => s + q.global, 0) / a.queueSamples.length;
    console.log(`  Global queue: max=${maxQ}, avg=${avgQ.toFixed(1)}, samples=${a.queueSamples.length}`);
    if (maxQ > 100) console.log('  ⚠ High queue depth — runtime may be overloaded');
  } else {
    console.log('  No queue samples');
  }
  console.log(`  Max local queue: ${a.maxLocalQueue}`);

  // ── Kernel scheduling wait ──
  console.log(`\n${'─'.repeat(60)}`);
  console.log(`KERNEL SCHEDULING WAIT`);
  console.log(`${'─'.repeat(60)}`);
  for (const w of workerIds) {
    const parks = workerSpans[w].parks.filter(p => p.schedWait > 0);
    if (parks.length === 0) continue;
    const waits = parks.map(p => p.schedWait).sort((a, b) => b - a);
    const max = waits[0];
    const p50 = waits[Math.floor(waits.length * 0.5)];
    // schedWait is in ns
    console.log(`  Worker ${w}: max=${(max/1e6).toFixed(1)}ms, p50=${(p50/1e6).toFixed(2)}ms, ${waits.filter(w => w > 1e6).length} events > 1ms`);
  }

  console.log(`\n${'='.repeat(60)}`);
}

async function main() {
  const isDir = fs.statSync(TRACE_PATH).isDirectory();

  if (!isDir) {
    console.log(`Loading ${TRACE_PATH}...`);
    const trace = await parseTrace(TRACE_PATH);
    analyzeOne(trace, path.basename(TRACE_PATH));
  } else {
    const opts = { force: FORCE };
    if (SAMPLE) opts.sample = SAMPLE;
    opts.onProgress = ({ done, total, file }) => {
      if (done === 0) {
        console.log(`Found ${total} trace file(s)`);
      } else {
        process.stderr.write(`\r  [${done}/${total}] ${file}`);
      }
    };

    console.log(`Analyzing directory: ${TRACE_PATH}`);
    const analysis = await parseTrace(TRACE_PATH, opts);
    process.stderr.write('\n');
    reportAnalysis(analysis, `${analysis.files.length} files in ${path.basename(TRACE_PATH)}`);
  }
}

main().catch(err => { console.error(err); process.exit(1); });
